disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name

opt_in_rules:
  - empty_count
  - explicit_init
  - explicit_type_interface
  - closure_spacing
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - nimble_operator
  - attributes
  - closure_end_indentation
  - closure_parameter_position
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - MyTune

excluded:
  - Pods
  - build
  - DerivedData
  - .build

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: false
  ignores_comments: false
  ignores_urls: true

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 40
  error: 60

cyclomatic_complexity:
  warning: 10
  error: 20

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID

force_cast: error
force_try: error
force_unwrapping: error

custom_rules:
  no_print:
    name: "No print statements"
    regex: '(print\()'
    message: "Use proper logging instead of print()"
    severity: warning

reporter: "xcode"
